apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: digital-femsa-gaia
  annotations:
    github.com/project-slug: dlopezby93/digital-femsa-gaia
spec:
  type: asyncapi
  lifecycle: production
  definition: './asyncapi.yaml'
  owner: 11pili-rose

