apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: digital-femsa-gaia
  annotations:
    github.com/project-slug: dlopezby93/digital-femsa-gaia
    asyncapi.io/documentation: './asyncapi.yml'
spec:
  type: other
  lifecycle: unknown
  owner: 11pili-rose
