apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: digital-femsa-gaia
  annotations:
    github.com/project-slug: dlopezby93/digital-femsa-gaia
    asyncapi.io/documentation: './asyncapi.yaml' # Ruta al archivo asyncapi.yaml
spec:
  type: asyncapi
  lifecycle: production
  owner: 11pili-rose

